# Innledning {#intro}

Publisering er en av kjerneoppgavene ved et universitet, og NTNUs forskere publiserer mye og bredt. Her er et utvalg av *typene* publisering vi ser blir registrert i den nasjonale publiseringsdatabasen Cristin: 
  * vitenskapelige arbeider i bøker, kapitler og tidsskrift
  * lærebøker og andre læringsressurser
  * faglige bidrag i leksika, fagtidsskrift eller håndbøker
  * rapporter
  * debattartikler, kronikker og kommentarer
  * lederartikler og anmeldelser

Diskusjonen rundt universitetenes publiseringsvirksomhet har en tendens til å kretse rundt produksjonen av vitenskapelige publikasjoner, og gjerne hvor mange publiseringspoeng disse er verdt i beregningen av publiseringsindikatoren. Denne rapporten er et forsøk på å utvide forståelsen av publisering ved NTNU bittelitt. 


Reference a figure by its code chunk label with the `fig:` prefix, e.g., see Figure \@ref(fig:nice-fig). Similarly, you can reference tables generated from `knitr::kable()`, e.g., see Table \@ref(tab:nice-tab).

You can write citations, too. For example, we are using the **bookdown** package in this sample book, which was built on top of R Markdown and **knitr** [@xie2015].
